
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadorproyecto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 8;
  public static final int For = 19;
  public static final int Numero = 26;
  public static final int Float = 5;
  public static final int Op_booleano = 30;
  public static final int Op_aritmeticos = 29;
  public static final int Identificador = 20;
  public static final int Int = 2;
  public static final int LlaveAbierta = 13;
  public static final int Coma = 17;
  public static final int Op_relacional = 28;
  public static final int P_coma = 16;
  public static final int Parentesis_cerrada = 12;
  public static final int Protected = 23;
  public static final int Parentesis_abierta = 11;
  public static final int Main = 15;
  public static final int EOF = 0;
  public static final int Op_atribucion = 32;
  public static final int Op_incremento = 31;
  public static final int If = 7;
  public static final int Private = 22;
  public static final int error = 1;
  public static final int Op_logico = 27;
  public static final int Switch = 25;
  public static final int LlaveCerrada = 14;
  public static final int Do = 18;
  public static final int Void = 24;
  public static final int Public = 21;
  public static final int Igual = 10;
  public static final int While = 9;
  public static final int String = 4;
  public static final int Error = 6;
  public static final int Boolean = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Int",
  "Boolean",
  "String",
  "Float",
  "Error",
  "If",
  "Else",
  "While",
  "Igual",
  "Parentesis_abierta",
  "Parentesis_cerrada",
  "LlaveAbierta",
  "LlaveCerrada",
  "Main",
  "P_coma",
  "Coma",
  "Do",
  "For",
  "Identificador",
  "Public",
  "Private",
  "Protected",
  "Void",
  "Switch",
  "Numero",
  "Op_logico",
  "Op_relacional",
  "Op_aritmeticos",
  "Op_booleano",
  "Op_incremento",
  "Op_atribucion"
  };
}

